import sys

'''Based on a rewards.txt file generated by Output.py, outputs the fraction of successful episodes'''

if len(sys.argv) > 2:
	limit = int(sys.argv[2])
else:
	limit = -1
	
length = 0
successes = 0
fails = 0

with open(sys.argv[1], 'r') as f:
	for line in f:
		if limit > 0 and length == limit:
			break
		e, reward = line.split()
		reward = float(reward)
		length += 1
		if reward >= 0:
			successes += 1
		else:
			fails += 1
	print float(successes)/length

print successes, fails, length
